In [4]:
import pandas as pd

In [5]:
SURVEY = pd.read_csv('lv2-2403.csv')

In [6]:
SURVEY.shape

(11351, 11)

In [7]:
SURVEY.head()

,D_ID,HOBBY,OPENSOURCE,CORPORATE,YEARS,SATIS,SALARY,MONITORS,TOOL,GENDER,AGE
0,1,1,1,0,0-2 years,4.5,NaN,1,Git,Female,25-34 years old
1,2,1,0,0,18-20 years,2.8,75000.0,3,Git,NaN,over 35
2,3,1,0,0,3-5 years,6.4,10958.0,1,Git,NaN,25-34 years old
3,4,1,1,0,9-11 years,4.0,NaN,2,Git,NaN,over 35
4,5,1,0,1,6-8 years,1.5,44000.0,2,Git;Zip file back-ups,Female,under 25

# Q1

In [8]:
df_1 = SURVEY.copy()

# 1-1

In [9]:
DF1 = df_1.dropna(subset='SALARY')

In [10]:
DF1.shape

(8526, 11)

# 1-2

In [11]:
AVG1 = DF1['SALARY'].mean()

In [12]:
AVG1

np.float64(98525.35186488388)

# 1-3

In [13]:
import numpy as np

In [14]:
years = DF1['YEARS'].value_counts().reset_index()['YEARS']

In [15]:
years

0            3-5 years
1            6-8 years
2           9-11 years
3          12-14 years
4          15-17 years
5            0-2 years
6          18-20 years
7     30 or more years
8          21-23 years
9          24-26 years
10         27-29 years
Name: YEARS, dtype: object

In [16]:
for year in years:
    DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)

C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_27252\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_27252\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_27252\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_27252\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_27252\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_27252\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_27252\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_27252\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_27252\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_27252\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_27252\4169026702.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF1['IN'] = np.where((DF1['SALARY'] > DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) - DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5) & (DF1['SALARY'] < DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.mean()) + DF1.groupby('YEARS')['SALARY'].transform(lambda x: x.std()) * 1.5), 1, 0)

In [17]:
DF1

,D_ID,HOBBY,OPENSOURCE,CORPORATE,YEARS,SATIS,SALARY,MONITORS,TOOL,GENDER,AGE,IN
1,2,1,0,0,18-20 years,2.8,75000.0,3,Git,NaN,over 35,1
2,3,1,0,0,3-5 years,6.4,10958.0,1,Git,NaN,25-34 years old,1
4,5,1,0,1,6-8 years,1.5,44000.0,2,Git;Zip file back-ups,Female,under 25,1
5,6,0,0,1,3-5 years,1.5,60000.0,2,Git,Female,25-34 years old,1
6,7,1,1,0,15-17 years,6.4,90000.0,2,Git,NaN,25-34 years old,1
...,...,...,...,...,...,...,...,...,...,...,...,...
11343,11344,1,0,0,21-23 years,6.2,67313.0,2,Git,Male,over 35,1
11344,11345,1,0,0,9-11 years,6.6,31788.0,1,I don't use version control,Male,25-34 years old,1
11346,11347,1,1,0,18-20 years,6.4,70000.0,1,Git,Female,over 35,1
11347,11348,0,0,0,30 or more years,1.6,80000.0,3,Git,Male,over 35,1
11350,11351,1,1,0,30 or more years,1.6,85000.0,2,Git,Male,over 35,1

In [18]:
DF1['IN'].value_counts()

IN
1    8214
0     312
Name: count, dtype: int64

In [19]:
DF1 = DF1[DF1['IN'] == 1].copy()

In [20]:
DF1 = DF1.drop(columns=['IN'])

# 1-4

In [21]:
AVG2 = DF1['SALARY'].mean()

In [22]:
abs(AVG1 - AVG2)

np.float64(34470.182519863185)

# Q1 Answer

In [23]:
print(round(abs(AVG1 - AVG2)))

34470

# Q2

In [24]:
df_2 = SURVEY.copy()

# 2-1

In [25]:
DF2 = df_2[df_2['AGE'] == '25-34 years old']

In [26]:
DF2.shape

(6209, 11)

# 2-2

In [27]:
df2_tmp = DF2.dropna(subset='SALARY')

In [28]:
df2_median = df2_tmp['SALARY'].median()

In [29]:
DF2['SALARY'] = DF2['SALARY'].fillna(value=df2_median)

C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_27252\1521987472.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF2['SALARY'] = DF2['SALARY'].fillna(value=df2_median)

In [30]:
df2_tmp = DF2.dropna(subset='SALARY')

In [31]:
df2_tmp.shape

(6209, 11)

In [32]:
DF2 = DF2.sort_values(by='D_ID').reset_index(drop=True)

In [33]:
DF2

,D_ID,HOBBY,OPENSOURCE,CORPORATE,YEARS,SATIS,SALARY,MONITORS,TOOL,GENDER,AGE
0,1,1,1,0,0-2 years,4.5,56277.0,1,Git,Female,25-34 years old
1,3,1,0,0,3-5 years,6.4,10958.0,1,Git,NaN,25-34 years old
2,6,0,0,1,3-5 years,1.5,60000.0,2,Git,Female,25-34 years old
3,7,1,1,0,15-17 years,6.4,90000.0,2,Git,NaN,25-34 years old
4,8,1,1,1,12-14 years,6.1,120000.0,2,Git;Subversion;Zip file back-ups,Male,25-34 years old
...,...,...,...,...,...,...,...,...,...,...,...
6204,11339,1,0,0,6-8 years,2.0,29170.0,2,Team Foundation Version Control,Male,25-34 years old
6205,11340,0,0,0,9-11 years,1.2,12000.0,1,Zip file back-ups,Male,25-34 years old
6206,11341,1,1,0,15-17 years,7.4,87000.0,2,Git;Mercurial,Male,25-34 years old
6207,11345,1,0,0,9-11 years,6.6,31788.0,1,I don't use version control,Male,25-34 years old
6208,11349,1,1,0,18-20 years,6.3,56277.0,1,Git,Female,25-34 years old

In [40]:
DF2['TOOL_CNT'] = DF2['TOOL'].map(lambda x: len(x.split(';')))

In [41]:
DF2.head()

,D_ID,HOBBY,OPENSOURCE,CORPORATE,YEARS,SATIS,SALARY,MONITORS,TOOL,GENDER,AGE,SATIS_S,SALARY_S,MONITORS_S,TOOL_CNT
0,1,1,1,0,0-2 years,4.5,56277.0,1,Git,Female,25-34 years old,-0.297065,-0.164405,-1.315537,1
1,3,1,0,0,3-5 years,6.4,10958.0,1,Git,NaN,25-34 years old,0.784272,-0.425231,-1.315537,1
2,6,0,0,1,3-5 years,1.5,60000.0,2,Git,Female,25-34 years old,-2.004439,-0.142978,0.150921,1
3,7,1,1,0,15-17 years,6.4,90000.0,2,Git,NaN,25-34 years old,0.784272,0.029682,0.150921,1
4,8,1,1,1,12-14 years,6.1,120000.0,2,Git;Subversion;Zip file back-ups,Male,25-34 years old,0.613535,0.202341,0.150921,3

# 2-4

In [42]:
targets = ['SATIS', 'SALARY', 'MONITORS', 'TOOL_CNT']

In [43]:
from sklearn.preprocessing import StandardScaler

In [44]:
for target in targets:
    DF2[target + '_S'] = StandardScaler().fit_transform(X=DF2.loc[:, [target]])

In [45]:
DF2.head()

,D_ID,HOBBY,OPENSOURCE,CORPORATE,YEARS,SATIS,SALARY,MONITORS,TOOL,GENDER,AGE,SATIS_S,SALARY_S,MONITORS_S,TOOL_CNT,TOOL_CNT_S
0,1,1,1,0,0-2 years,4.5,56277.0,1,Git,Female,25-34 years old,-0.297065,-0.164405,-1.315537,1,-0.560267
1,3,1,0,0,3-5 years,6.4,10958.0,1,Git,NaN,25-34 years old,0.784272,-0.425231,-1.315537,1,-0.560267
2,6,0,0,1,3-5 years,1.5,60000.0,2,Git,Female,25-34 years old,-2.004439,-0.142978,0.150921,1,-0.560267
3,7,1,1,0,15-17 years,6.4,90000.0,2,Git,NaN,25-34 years old,0.784272,0.029682,0.150921,1,-0.560267
4,8,1,1,1,12-14 years,6.1,120000.0,2,Git;Subversion;Zip file back-ups,Male,25-34 years old,0.613535,0.202341,0.150921,3,2.467322

# 2-5

In [46]:
targets = ['SATIS_S', 'SALARY_S', 'MONITORS_S', 'TOOL_CNT_S']

In [47]:
from sklearn.cluster import KMeans

In [49]:
model = KMeans(n_clusters=2, random_state=1234).fit(X=DF2.loc[:, targets])

In [50]:
DF2['LABEL'] = model.predict(X=DF2.loc[:, targets])

In [51]:
DF2.head()

,D_ID,HOBBY,OPENSOURCE,CORPORATE,YEARS,SATIS,SALARY,MONITORS,TOOL,GENDER,AGE,SATIS_S,SALARY_S,MONITORS_S,TOOL_CNT,TOOL_CNT_S,LABEL
0,1,1,1,0,0-2 years,4.5,56277.0,1,Git,Female,25-34 years old,-0.297065,-0.164405,-1.315537,1,-0.560267,1
1,3,1,0,0,3-5 years,6.4,10958.0,1,Git,NaN,25-34 years old,0.784272,-0.425231,-1.315537,1,-0.560267,1
2,6,0,0,1,3-5 years,1.5,60000.0,2,Git,Female,25-34 years old,-2.004439,-0.142978,0.150921,1,-0.560267,0
3,7,1,1,0,15-17 years,6.4,90000.0,2,Git,NaN,25-34 years old,0.784272,0.029682,0.150921,1,-0.560267,1
4,8,1,1,1,12-14 years,6.1,120000.0,2,Git;Subversion;Zip file back-ups,Male,25-34 years old,0.613535,0.202341,0.150921,3,2.467322,1

In [52]:
DF2.groupby('LABEL')['GENDER'].value_counts()

LABEL  GENDER
0      Male       988
       Female     542
1      Male      2496
       Female    1327
Name: count, dtype: int64

# 2-6

In [53]:
abs(988/542*100 - 2496/1327*100)

5.8056209800982685

# Q2 Answer

In [54]:
print(round(abs(988/542*100 - 2496/1327*100), 2))

5.81

# Q3

In [55]:
df_3 = SURVEY.copy()

# 3-1

In [56]:
df_3 = df_3.dropna(subset=['GENDER', 'SALARY'])

In [57]:
df_3.shape

(7431, 11)

In [58]:
df_3['GIT_YN'] = df_3['TOOL'].map(lambda x: ('Git' in x ) + 0)

C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_27252\3495185334.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_3['GIT_YN'] = df_3['TOOL'].map(lambda x: ('Git' in x ) + 0)

In [60]:
df_3.head(15)

,D_ID,HOBBY,OPENSOURCE,CORPORATE,YEARS,SATIS,SALARY,MONITORS,TOOL,GENDER,AGE,GIT_YN
4,5,1,0,1,6-8 years,1.5,44000.0,2,Git;Zip file back-ups,Female,under 25,1
5,6,0,0,1,3-5 years,1.5,60000.0,2,Git,Female,25-34 years old,1
7,8,1,1,1,12-14 years,6.1,120000.0,2,Git;Subversion;Zip file back-ups,Male,25-34 years old,1
8,9,1,0,1,15-17 years,6.0,52627.0,3,Git,Male,over 35,1
9,10,1,1,0,6-8 years,4.0,120000.0,1,Git,Male,under 25,1
10,11,1,1,1,6-8 years,6.3,34440.0,2,Git,Male,25-34 years old,1
11,12,1,1,1,21-23 years,6.3,110000.0,3,Git,Male,25-34 years old,1
15,16,0,1,0,12-14 years,2.3,39648.0,3,Git,Male,25-34 years old,1
17,18,1,1,0,3-5 years,1.5,18780.0,1,Git,Male,25-34 years old,1
18,19,1,1,0,3-5 years,6.1,3569.0,1,Git;Copying and pasting files to network shares,Female,25-34 years old,1
19,20,1,0,1,9-11 years,6.2,1140000.0,3,Subversion,Male,over 35,0
20,21,1,1,0,12-14 years,6.4,79552.0,2,Git,Male,under 25,1
21,22,0,0,1,15-17 years,5.8,46963.0,1,Git,Female,25-34 years old,1
22,23,1,0,1,3-5 years,2.4,65000.0,3,Git;Copying and pasting files to network shares,Female,25-34 years old,1
23,24,0,0,0,12-14 years,6.8,52783.0,3,Git,Male,25-34 years old,1

# 3-3

In [61]:
targets = ['YEARS', 'GENDER', 'AGE']

In [62]:
df_3 = pd.get_dummies(df_3, drop_first=False, dtype='int', columns=targets)

In [63]:
df_3

,D_ID,HOBBY,OPENSOURCE,CORPORATE,SATIS,SALARY,MONITORS,TOOL,GIT_YN,YEARS_0-2 years,...,YEARS_27-29 years,YEARS_3-5 years,YEARS_30 or more years,YEARS_6-8 years,YEARS_9-11 years,GENDER_Female,GENDER_Male,AGE_25-34 years old,AGE_over 35,AGE_under 25
4,5,1,0,1,1.5,44000.0,2,Git;Zip file back-ups,1,0,...,0,0,0,1,0,1,0,0,0,1
5,6,0,0,1,1.5,60000.0,2,Git,1,0,...,0,1,0,0,0,1,0,1,0,0
7,8,1,1,1,6.1,120000.0,2,Git;Subversion;Zip file back-ups,1,0,...,0,0,0,0,0,0,1,1,0,0
8,9,1,0,1,6.0,52627.0,3,Git,1,0,...,0,0,0,0,0,0,1,0,1,0
9,10,1,1,0,4.0,120000.0,1,Git,1,0,...,0,0,0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11343,11344,1,0,0,6.2,67313.0,2,Git,1,0,...,0,0,0,0,0,0,1,0,1,0
11344,11345,1,0,0,6.6,31788.0,1,I don't use version control,0,0,...,0,0,0,0,1,0,1,1,0,0
11346,11347,1,1,0,6.4,70000.0,1,Git,1,0,...,0,0,0,0,0,1,0,0,1,0
11347,11348,0,0,0,1.6,80000.0,3,Git,1,0,...,0,0,1,0,0,0,1,0,1,0
11350,11351,1,1,0,1.6,85000.0,2,Git,1,0,...,0,0,1,0,0,0,1,0,1,0

# 3-4

In [64]:
TRAIN3=df_3[df_3['D_ID'] % 3 != 0]
TEST3=df_3[df_3['D_ID'] % 3 == 0]

In [65]:
TRAIN3.shape

(4917, 25)

In [66]:
TEST3.shape

(2514, 25)

# 3-5

In [67]:
TRAIN3.columns

Index(['D_ID', 'HOBBY', 'OPENSOURCE', 'CORPORATE', 'SATIS', 'SALARY',
       'MONITORS', 'TOOL', 'GIT_YN', 'YEARS_0-2 years', 'YEARS_12-14 years',
       'YEARS_15-17 years', 'YEARS_18-20 years', 'YEARS_21-23 years',
       'YEARS_24-26 years', 'YEARS_27-29 years', 'YEARS_3-5 years',
       'YEARS_30 or more years', 'YEARS_6-8 years', 'YEARS_9-11 years',
       'GENDER_Female', 'GENDER_Male', 'AGE_25-34 years old', 'AGE_over 35',
       'AGE_under 25'],
      dtype='object')

In [68]:
targets = ['HOBBY', 'OPENSOURCE', 'CORPORATE', 'SALARY', 'MONITORS', 'GIT_YN', 'YEARS_0-2 years', 'YEARS_12-14 years',
       'YEARS_15-17 years', 'YEARS_18-20 years', 'YEARS_21-23 years',
       'YEARS_24-26 years', 'YEARS_27-29 years', 'YEARS_3-5 years',
       'YEARS_30 or more years', 'YEARS_6-8 years', 'YEARS_9-11 years',
       'GENDER_Female', 'GENDER_Male', 'AGE_25-34 years old', 'AGE_over 35',
       'AGE_under 25']

In [69]:
targets

['HOBBY',
 'OPENSOURCE',
 'CORPORATE',
 'SALARY',
 'MONITORS',
 'GIT_YN',
 'YEARS_0-2 years',
 'YEARS_12-14 years',
 'YEARS_15-17 years',
 'YEARS_18-20 years',
 'YEARS_21-23 years',
 'YEARS_24-26 years',
 'YEARS_27-29 years',
 'YEARS_3-5 years',
 'YEARS_30 or more years',
 'YEARS_6-8 years',
 'YEARS_9-11 years',
 'GENDER_Female',
 'GENDER_Male',
 'AGE_25-34 years old',
 'AGE_over 35',
 'AGE_under 25']

In [70]:
len(targets)

22

In [71]:
from sklearn.tree import DecisionTreeRegressor

In [72]:
model = DecisionTreeRegressor(max_depth=7, random_state=1234).fit(y=TRAIN3['SATIS'], X=TRAIN3.loc[:, targets])

# 3-6

In [73]:
from sklearn.metrics import mean_absolute_percentage_error

In [74]:
pred = model.predict(X=TEST3.loc[:, targets])

In [75]:
mean_absolute_percentage_error(y_true=TEST3['SATIS'], y_pred=pred) * 100

51.3254981425455

# Q3

In [77]:
print(round(mean_absolute_percentage_error(y_true=TEST3['SATIS'], y_pred=pred) * 100, 1))

51.3