In [1]:
import pandas as pd

In [2]:
EXPT = pd.read_csv('lv2-2410.csv')

In [3]:
EXPT.shape

(7886, 13)

In [4]:
EXPT.head()

,PID,MOTOR_SPEED,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11
0,1,-1.222430,-0.239430,-1.004377,-1.121654,0.323488,-1.299336,1.029205,-0.245735,-2.442078,-1.829724,-2.061447,-2.010500
1,2,-1.222429,-0.239603,-1.003756,-1.121233,0.323055,-1.300406,1.029195,-0.245716,-2.442082,-1.829416,-2.060997,-2.010185
2,3,-1.222431,-0.239101,-1.003189,-1.121282,0.323732,-1.298815,1.029176,-0.245731,-2.441782,-1.829656,-2.060787,-2.009808
3,4,-1.222431,-0.239626,-1.003351,-1.121051,0.323116,-1.300885,1.029179,-0.245715,-2.441530,-1.829491,-2.061134,-2.009828
4,5,-1.222430,-0.238890,-1.002573,-1.120491,0.323869,-1.298650,1.029182,-0.245706,-2.441859,-1.830280,-2.061540,-2.009796

# Q1

In [5]:
df_1 = EXPT.copy()

# 1-1

In [6]:
df_1.columns

Index(['PID', 'MOTOR_SPEED', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8',
       'F9', 'F10', 'F11'],
      dtype='object')

In [7]:
targets = ['MOTOR_SPEED', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11']

In [8]:
len(targets)

12

In [9]:
cvs = []

for target in targets:
    s = df_1[target].std()
    m = df_1[target].mean()
    cv = s / m
    cvs.append(cv)

In [10]:
cvs

[np.float64(-11.775367294141931),
 np.float64(2.2004497543376407),
 np.float64(-0.10780218598081145),
 np.float64(-0.0158353134821319),
 np.float64(-1.9401933693275466),
 np.float64(12.051347810837322),
 np.float64(12.19174577231294),
 np.float64(2.2547530574928447),
 np.float64(-0.4316831173323458),
 np.float64(-0.19021715735795452),
 np.float64(-0.32712781749264536),
 np.float64(-0.48059749261577384)]

# 1-2

In [11]:
abs_cvs = []

for cv in cvs:
    abs_cvs.append(abs(cv))

In [13]:
abs_cvs

[np.float64(11.775367294141931),
 np.float64(2.2004497543376407),
 np.float64(0.10780218598081145),
 np.float64(0.0158353134821319),
 np.float64(1.9401933693275466),
 np.float64(12.051347810837322),
 np.float64(12.19174577231294),
 np.float64(2.2547530574928447),
 np.float64(0.4316831173323458),
 np.float64(0.19021715735795452),
 np.float64(0.32712781749264536),
 np.float64(0.48059749261577384)]

In [14]:
max(abs_cvs)

np.float64(12.19174577231294)

# Q1 Answer

In [16]:
print(round(max(abs_cvs), 2))

12.19

# Q2

In [17]:
df_2 = EXPT.copy()

# 2-1

In [22]:
df_2['HIGH_SPEED'] = (df_2['MOTOR_SPEED'] > 1) + 0

In [23]:
df_2.head()

,PID,MOTOR_SPEED,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,HIGH_SPEED
0,1,-1.222430,-0.239430,-1.004377,-1.121654,0.323488,-1.299336,1.029205,-0.245735,-2.442078,-1.829724,-2.061447,-2.010500,0
1,2,-1.222429,-0.239603,-1.003756,-1.121233,0.323055,-1.300406,1.029195,-0.245716,-2.442082,-1.829416,-2.060997,-2.010185,0
2,3,-1.222431,-0.239101,-1.003189,-1.121282,0.323732,-1.298815,1.029176,-0.245731,-2.441782,-1.829656,-2.060787,-2.009808,0
3,4,-1.222431,-0.239626,-1.003351,-1.121051,0.323116,-1.300885,1.029179,-0.245715,-2.441530,-1.829491,-2.061134,-2.009828,0
4,5,-1.222430,-0.238890,-1.002573,-1.120491,0.323869,-1.298650,1.029182,-0.245706,-2.441859,-1.830280,-2.061540,-2.009796,0

# 2-2

In [26]:
TRAIN25 = df_2[df_2['PID'] % 5 != 0].copy()
TEST25 = df_2[df_2['PID'] % 5 == 0].copy()

In [27]:
TRAIN25.shape

(6309, 14)

In [28]:
TEST25.shape

(1577, 14)

# 2-3

In [29]:
from sklearn.tree import DecisionTreeClassifier

In [30]:
df_2.columns

Index(['PID', 'MOTOR_SPEED', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8',
       'F9', 'F10', 'F11', 'HIGH_SPEED'],
      dtype='object')

In [31]:
targets = ['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11']

In [32]:
model = DecisionTreeClassifier(max_depth=3, random_state=1234).fit(y=TRAIN25['HIGH_SPEED'], X=TRAIN25.loc[:, targets])

# 2-4

In [33]:
pred = model.predict(X=TEST25.loc[:, targets])

In [34]:
from sklearn.metrics import recall_score

In [36]:
rec = recall_score(y_true=TEST25['HIGH_SPEED'], y_pred=pred)

In [37]:
rec

0.9438202247191011

# Q2 Answer

In [38]:
print(round(rec, 3))

0.944

# Q3

In [39]:
df_3 = EXPT.copy()

# 3-1

In [40]:
targets = ['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11']

In [47]:
df_3['TMP'] = df_3['PID'].map(lambda x: 0)

In [48]:
df_3.head()

,PID,MOTOR_SPEED,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,TMP
0,1,-1.222430,-0.239430,-1.004377,-1.121654,0.323488,-1.299336,1.029205,-0.245735,-2.442078,-1.829724,-2.061447,-2.010500,0
1,2,-1.222429,-0.239603,-1.003756,-1.121233,0.323055,-1.300406,1.029195,-0.245716,-2.442082,-1.829416,-2.060997,-2.010185,0
2,3,-1.222431,-0.239101,-1.003189,-1.121282,0.323732,-1.298815,1.029176,-0.245731,-2.441782,-1.829656,-2.060787,-2.009808,0
3,4,-1.222431,-0.239626,-1.003351,-1.121051,0.323116,-1.300885,1.029179,-0.245715,-2.441530,-1.829491,-2.061134,-2.009828,0
4,5,-1.222430,-0.238890,-1.002573,-1.120491,0.323869,-1.298650,1.029182,-0.245706,-2.441859,-1.830280,-2.061540,-2.009796,0

In [49]:
for target in targets:
    df_3['TMP'] += (df_3[target] > 1.5) + 0

In [50]:
df_3['TMP'].value_counts()

TMP
0    7018
2     517
1     351
Name: count, dtype: int64

In [51]:
DF26 = df_3[df_3['TMP'] == 0]

In [53]:
DF26 = DF26.drop(columns=['TMP'])

In [57]:
DF26.shape

(7018, 13)

In [54]:
DF26.head()

,PID,MOTOR_SPEED,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11
0,1,-1.222430,-0.239430,-1.004377,-1.121654,0.323488,-1.299336,1.029205,-0.245735,-2.442078,-1.829724,-2.061447,-2.010500
1,2,-1.222429,-0.239603,-1.003756,-1.121233,0.323055,-1.300406,1.029195,-0.245716,-2.442082,-1.829416,-2.060997,-2.010185
2,3,-1.222431,-0.239101,-1.003189,-1.121282,0.323732,-1.298815,1.029176,-0.245731,-2.441782,-1.829656,-2.060787,-2.009808
3,4,-1.222431,-0.239626,-1.003351,-1.121051,0.323116,-1.300885,1.029179,-0.245715,-2.441530,-1.829491,-2.061134,-2.009828
4,5,-1.222430,-0.238890,-1.002573,-1.120491,0.323869,-1.298650,1.029182,-0.245706,-2.441859,-1.830280,-2.061540,-2.009796

# 3-2

In [55]:
TRAIN26 = DF26[DF26['PID'] % 6 != 0]
TEST26 = DF26[DF26['PID'] % 6 == 0]

In [56]:
TRAIN26.shape

(5844, 13)

In [58]:
TEST26.shape

(1174, 13)

# 3-3

In [59]:
from sklearn.linear_model import LinearRegression

In [60]:
targets = ['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11']

In [61]:
model = LinearRegression().fit(y=TRAIN26['MOTOR_SPEED'], X=TRAIN26.loc[:, targets])

# 3-4

In [62]:
pred = model.predict(X=TEST26.loc[:, targets])

In [63]:
from sklearn.metrics import mean_absolute_error

In [64]:
mae = mean_absolute_error(y_true=TEST26['MOTOR_SPEED'], y_pred=pred)

In [65]:
mae

0.11438522483446703

# Q3 Answer

In [66]:
print(round(mae, 3))

0.114