In [1]:
import pandas as pd

In [2]:
REF = pd.read_csv('lv2-2406.csv')

In [3]:
REF.shape

(8124, 16)

In [4]:
REF.head()

,PRD_ID,CLASS,PART00,PART01,PART02,PART03,PART04,PART05,PART06,PART07,PART08,PART09,PART10,PART11,PART12,PART13
0,1,B,C,C,A,B,B,B,B,C,B,D,C,B,B,D
1,2,G,C,C,A,B,B,A,B,B,B,D,C,B,B,A
2,3,G,B,C,A,B,B,A,B,B,B,D,C,B,B,A
3,4,B,C,B,A,B,B,B,B,C,B,D,C,B,B,D
4,5,G,C,C,B,B,A,A,A,C,B,D,C,B,C,B

# Q1

In [5]:
df_1 = REF.copy()

In [6]:
df_1.columns

Index(['PRD_ID', 'CLASS', 'PART00', 'PART01', 'PART02', 'PART03', 'PART04',
       'PART05', 'PART06', 'PART07', 'PART08', 'PART09', 'PART10', 'PART11',
       'PART12', 'PART13'],
      dtype='object')

# 1-1

In [7]:
from math import log2

In [8]:
targets = ['PART02', 'PART03', 'PART04', 'PART05', 'PART06']

In [9]:
ref_count = df_1.shape[0]

In [11]:
df_1[df_1['PART02'] == 'A']['PRD_ID'].count()

np.int64(3376)

In [14]:
ents = []

for target in targets:
    c_a = df_1[df_1[target] == 'A']['PRD_ID'].count()
    c_b = df_1[df_1[target] == 'B']['PRD_ID'].count()
    c_a_g = df_1[(df_1[target] == 'A') & (df_1['CLASS'] == 'G')]['PRD_ID'].count()
    c_a_b = df_1[(df_1[target] == 'A') & (df_1['CLASS'] == 'B')]['PRD_ID'].count()
    c_b_g = df_1[(df_1[target] == 'B') & (df_1['CLASS'] == 'G')]['PRD_ID'].count()
    c_b_b = df_1[(df_1[target] == 'B') & (df_1['CLASS'] == 'B')]['PRD_ID'].count()
    p_a_g = c_a_g / c_a
    p_a_b = c_a_b / c_a
    p_b_g = c_b_g / c_b
    p_b_b = c_b_b / c_b
    e_a = (p_a_g * log2(p_a_g) + p_a_b * log2(p_a_b)) * -1
    e_b = (p_b_g * log2(p_b_g) + p_b_b * log2(p_b_b)) * -1
    entropy = (c_a / ref_count * e_a) + (c_b / ref_count * e_b)
    ents.append(entropy)

In [15]:
ents

[np.float64(0.8066884111112408),
 np.float64(0.9849028696218441),
 np.float64(0.8981847128758901),
 np.float64(0.7689135217244143),
 np.float64(0.9915511243027961)]

# 1-2

In [40]:
max(ents) + min(ents)

np.float64(1.7604646460272104)

# Q1 Answer

In [41]:
print(round(max(ents) + min(ents), 2))

1.76

# Q2

In [42]:
df_2 = REF.copy()

In [43]:
df_2.columns

Index(['PRD_ID', 'CLASS', 'PART00', 'PART01', 'PART02', 'PART03', 'PART04',
       'PART05', 'PART06', 'PART07', 'PART08', 'PART09', 'PART10', 'PART11',
       'PART12', 'PART13'],
      dtype='object')

# 2-1

In [44]:
targets = ['PART00', 'PART01', 'PART07', 'PART08', 'PART09']

In [45]:
df_2 = pd.get_dummies(df_2, drop_first=True, columns=targets, dtype='int')

In [46]:
df_2.head()

,PRD_ID,CLASS,PART02,PART03,PART04,PART05,PART06,PART10,PART11,PART12,...,PART08_C,PART08_D,PART09_B,PART09_C,PART09_D,PART09_E,PART09_F,PART09_G,PART09_H,PART09_I
0,1,B,A,B,B,B,B,C,B,B,...,0,0,0,0,1,0,0,0,0,0
1,2,G,A,B,B,A,B,C,B,B,...,0,0,0,0,1,0,0,0,0,0
2,3,G,A,B,B,A,B,C,B,B,...,0,0,0,0,1,0,0,0,0,0
3,4,B,A,B,B,B,B,C,B,B,...,0,0,0,0,1,0,0,0,0,0
4,5,G,B,B,A,A,A,C,B,C,...,0,0,0,0,1,0,0,0,0,0

In [47]:
df_2.columns

Index(['PRD_ID', 'CLASS', 'PART02', 'PART03', 'PART04', 'PART05', 'PART06',
       'PART10', 'PART11', 'PART12', 'PART13', 'PART00_B', 'PART00_C',
       'PART00_D', 'PART00_E', 'PART00_F', 'PART01_B', 'PART01_C', 'PART01_D',
       'PART07_B', 'PART07_C', 'PART07_D', 'PART07_E', 'PART08_B', 'PART08_C',
       'PART08_D', 'PART09_B', 'PART09_C', 'PART09_D', 'PART09_E', 'PART09_F',
       'PART09_G', 'PART09_H', 'PART09_I'],
      dtype='object')

In [48]:
df_2.columns[-23:]

Index(['PART00_B', 'PART00_C', 'PART00_D', 'PART00_E', 'PART00_F', 'PART01_B',
       'PART01_C', 'PART01_D', 'PART07_B', 'PART07_C', 'PART07_D', 'PART07_E',
       'PART08_B', 'PART08_C', 'PART08_D', 'PART09_B', 'PART09_C', 'PART09_D',
       'PART09_E', 'PART09_F', 'PART09_G', 'PART09_H', 'PART09_I'],
      dtype='object')

# 2-2

In [49]:
targets = df_2.columns[-23:]

In [50]:
targets

Index(['PART00_B', 'PART00_C', 'PART00_D', 'PART00_E', 'PART00_F', 'PART01_B',
       'PART01_C', 'PART01_D', 'PART07_B', 'PART07_C', 'PART07_D', 'PART07_E',
       'PART08_B', 'PART08_C', 'PART08_D', 'PART09_B', 'PART09_C', 'PART09_D',
       'PART09_E', 'PART09_F', 'PART09_G', 'PART09_H', 'PART09_I'],
      dtype='object')

In [54]:
g_effs = []

for target in targets:
    prob_g0 = df_2[(df_2['CLASS'] == 'G') & (df_2[target] == 0)][target].count() / df_2[df_2[target] == 0][target].count()
    prob_g1 = df_2[(df_2['CLASS'] == 'G') & (df_2[target] == 1)][target].count() / df_2[df_2[target] == 1][target].count()
    g_eff = max(prob_g1/(prob_g0 + 0.01), prob_g0/(prob_g1 + 0.01))
    g_effs.append(g_eff)

In [55]:
len(g_effs)

23

In [56]:
g_effs[:5]

[np.float64(1.7670108475445756),
 np.float64(1.0329642634876064),
 np.float64(1.0174238812457903),
 np.float64(1.9116202453823739),
 np.float64(51.822660098522164)]

# 2-3

In [57]:
g_effs.sort(reverse=True)

In [62]:
len(g_effs[:10])

10

In [64]:
g_effs[:10]

[np.float64(54.706188247529894),
 np.float64(52.02769535113749),
 np.float64(51.95061728395061),
 np.float64(51.822660098522164),
 np.float64(51.822660098522164),
 np.float64(9.992281327213679),
 np.float64(4.032619061520795),
 np.float64(3.4698541706180897),
 np.float64(2.057792045163024),
 np.float64(1.9368449840305522)]

In [66]:
import numpy as np

In [67]:
np.mean(g_effs[:10])

np.float64(28.381921266820843)

# Q2 Answer

In [68]:
print(round(np.mean(g_effs[:10]), 3))

28.382

# Q3

In [69]:
df_3 = REF.copy()

In [70]:
df_3.columns

Index(['PRD_ID', 'CLASS', 'PART00', 'PART01', 'PART02', 'PART03', 'PART04',
       'PART05', 'PART06', 'PART07', 'PART08', 'PART09', 'PART10', 'PART11',
       'PART12', 'PART13'],
      dtype='object')

# 3-1

In [71]:
targets = ['PART10', 'PART11', 'PART12', 'PART13']

In [72]:
df_3 = pd.get_dummies(data=df_3, columns=targets, drop_first=True, dtype='int')

In [73]:
df_3.head()

,PRD_ID,CLASS,PART00,PART01,PART02,PART03,PART04,PART05,PART06,PART07,...,PART11_C,PART12_B,PART12_C,PART12_D,PART12_E,PART13_B,PART13_C,PART13_D,PART13_E,PART13_F
0,1,B,C,C,A,B,B,B,B,C,...,0,1,0,0,0,0,0,1,0,0
1,2,G,C,C,A,B,B,A,B,B,...,0,1,0,0,0,0,0,0,0,0
2,3,G,B,C,A,B,B,A,B,B,...,0,1,0,0,0,0,0,0,0,0
3,4,B,C,B,A,B,B,B,B,C,...,0,1,0,0,0,0,0,1,0,0
4,5,G,C,C,B,B,A,A,A,C,...,0,0,1,0,0,1,0,0,0,0

In [75]:
df_3.columns[-14:]

Index(['PART10_B', 'PART10_C', 'PART10_D', 'PART11_B', 'PART11_C', 'PART12_B',
       'PART12_C', 'PART12_D', 'PART12_E', 'PART13_B', 'PART13_C', 'PART13_D',
       'PART13_E', 'PART13_F'],
      dtype='object')

# 3-2

In [76]:
TRAIN23 = df_3[df_3['PRD_ID'] % 5 != 0]
TEST23 = df_3[df_3['PRD_ID'] % 5 == 0]

In [77]:
TRAIN23.shape

(6500, 26)

In [78]:
TEST23.shape

(1624, 26)

# 3-3

In [80]:
from sklearn.tree import DecisionTreeClassifier

In [81]:
model = DecisionTreeClassifier(random_state=1234, max_depth=9).fit(y=TRAIN23['CLASS'], X=TRAIN23.iloc[:, -14:])

# 3-4

In [82]:
model.feature_importances_

array([0.00000000e+00, 9.74872846e-03, 5.71041026e-03, 3.90461684e-02,
       0.00000000e+00, 3.85221646e-01, 2.64631186e-01, 6.35289501e-03,
       0.00000000e+00, 0.00000000e+00, 3.70856409e-04, 1.72049865e-02,
       5.11451009e-02, 2.20568023e-01])

In [83]:
fi = pd.DataFrame(data=df_3.columns[-14:], columns=['feature'])

In [84]:
fi

     feature
0   PART10_B
1   PART10_C
2   PART10_D
3   PART11_B
4   PART11_C
5   PART12_B
6   PART12_C
7   PART12_D
8   PART12_E
9   PART13_B
10  PART13_C
11  PART13_D
12  PART13_E
13  PART13_F

In [85]:
fi['fi'] = model.feature_importances_

In [86]:
fi

     feature        fi
0   PART10_B  0.000000
1   PART10_C  0.009749
2   PART10_D  0.005710
3   PART11_B  0.039046
4   PART11_C  0.000000
5   PART12_B  0.385222
6   PART12_C  0.264631
7   PART12_D  0.006353
8   PART12_E  0.000000
9   PART13_B  0.000000
10  PART13_C  0.000371
11  PART13_D  0.017205
12  PART13_E  0.051145
13  PART13_F  0.220568

In [87]:
VAR23 = fi.sort_values(by=['fi'], ascending=False)

In [88]:
VAR23

     feature        fi
5   PART12_B  0.385222
6   PART12_C  0.264631
13  PART13_F  0.220568
12  PART13_E  0.051145
3   PART11_B  0.039046
11  PART13_D  0.017205
1   PART10_C  0.009749
7   PART12_D  0.006353
2   PART10_D  0.005710
10  PART13_C  0.000371
4   PART11_C  0.000000
0   PART10_B  0.000000
9   PART13_B  0.000000
8   PART12_E  0.000000

# 3-5

In [89]:
models = []

In [90]:
target_l = [5, 10, 14]

In [92]:
for l in target_l:
    model  = DecisionTreeClassifier(random_state=1234, max_depth=9).fit(y=TRAIN23['CLASS'], X=TRAIN23.loc[:, VAR23['feature'][:l]])
    models.append(model)

In [93]:
len(models)

3

# 3-6

In [94]:
accs = []

In [95]:
from sklearn.metrics import accuracy_score

In [96]:
index = 0
for model in models:
    l = target_l[index]
    pred = model.predict(X=TEST23.loc[:, VAR23['feature'][:l]])
    acc = accuracy_score(y_true=TEST23['CLASS'], y_pred=pred)
    accs.append(acc)
    index += 1

In [97]:
accs

[0.8983990147783252, 0.9039408866995073, 0.9039408866995073]

# Q3 Answer

In [98]:
print(round(np.mean(accs), 3))

0.902