In [1]:
import pandas as pd

In [2]:
INSPECTION = pd.read_csv('lv2-2409.csv')

In [3]:
INSPECTION.shape

(1541, 13)

In [4]:
INSPECTION.head()

,PROD_ID,P01,P02,P03,P04,P05,P06,P07,P08,P09,P10,P11,DEFECT
0,1,20.5,211.132445,472.106499,59016.780458,180.278488,0.004718,4.598,1.309762,0.657530,2.333201,0.286323,1
1,2,18.2,608.912622,1361.570015,102354.648132,27.941448,0.027554,4.406,1.340600,0.634973,2.407363,0.273838,1
2,3,22.0,105.816886,236.613750,18512.294286,65.706055,0.143739,4.892,1.332637,0.640673,1.518283,1.146991,0
3,4,18.8,461.907460,1032.856481,79985.334528,168.575485,0.026491,4.760,1.365668,0.617570,1.869691,0.861646,1
4,5,24.4,35.039264,78.350176,68753.886594,66.274681,0.055444,6.006,0.977089,1.020477,1.069472,0.884705,0

# Q1

In [5]:
df_1 = INSPECTION.copy()

In [18]:
diffs = []

In [13]:
df_1.columns

Index(['PROD_ID', 'P01', 'P02', 'P03', 'P04', 'P05', 'P06', 'P07', 'P08',
       'P09', 'P10', 'P11', 'DEFECT'],
      dtype='object')

# 1-1

In [14]:
targets = ['P01', 'P02', 'P03', 'P04', 'P05', 'P06', 'P07', 'P08', 'P09', 'P10', 'P11']

In [15]:
df_1_0 = df_1[df_1['DEFECT'] == 0].copy()
df_1_1 = df_1[df_1['DEFECT'] == 1].copy()

In [16]:
df_1_0.shape

(786, 13)

In [17]:
df_1_1.shape

(755, 13)

In [19]:
for target in targets:
    Q01 = df_1_0[target].quantile(q=0.25)
    Q02 = df_1_0[target].quantile(q=0.50)
    Q03 = df_1_0[target].quantile(q=0.75)
    Q11 = df_1_1[target].quantile(q=0.25)
    Q12 = df_1_1[target].quantile(q=0.50)
    Q13 = df_1_1[target].quantile(q=0.75)

    diff = abs(Q01-Q11) + abs(Q02-Q12) + abs(Q03-Q13)

    diffs.append(diff)

In [20]:
diffs

[np.float64(7.191999999999997),
 np.float64(433.14636879995004),
 np.float64(968.5447248441001),
 np.float64(39792.25405340415),
 np.float64(5.558886528024956),
 np.float64(0.156659025),
 np.float64(0.4277500000000005),
 np.float64(0.10906630892503033),
 np.float64(0.07631938427505658),
 np.float64(0.5597997421860097),
 np.float64(0.3565887661189999)]

In [21]:
len(diffs)

11

# 1-2

In [22]:
max(diffs)

np.float64(39792.25405340415)

# Q1 Answer

In [24]:
print(round(max(diffs)))

39792

# Q2

In [25]:
df_2 = INSPECTION.copy()

In [26]:
df_2.shape

(1541, 13)

In [27]:
df_2.head()

,PROD_ID,P01,P02,P03,P04,P05,P06,P07,P08,P09,P10,P11,DEFECT
0,1,20.5,211.132445,472.106499,59016.780458,180.278488,0.004718,4.598,1.309762,0.657530,2.333201,0.286323,1
1,2,18.2,608.912622,1361.570015,102354.648132,27.941448,0.027554,4.406,1.340600,0.634973,2.407363,0.273838,1
2,3,22.0,105.816886,236.613750,18512.294286,65.706055,0.143739,4.892,1.332637,0.640673,1.518283,1.146991,0
3,4,18.8,461.907460,1032.856481,79985.334528,168.575485,0.026491,4.760,1.365668,0.617570,1.869691,0.861646,1
4,5,24.4,35.039264,78.350176,68753.886594,66.274681,0.055444,6.006,0.977089,1.020477,1.069472,0.884705,0

# 2-1

In [28]:
targets = ['P01', 'P02', 'P03', 'P04', 'P05', 'P06', 'P07', 'P08', 'P09', 'P10', 'P11']

In [29]:
from sklearn.preprocessing import MinMaxScaler

In [31]:
for target in targets:
    df_2[target + '_N'] = MinMaxScaler().fit_transform(X=df_2.loc[:, [target]])

In [32]:
df_2.head()

,PROD_ID,P01,P02,P03,P04,P05,P06,P07,P08,P09,...,P02_N,P03_N,P04_N,P05_N,P06_N,P07_N,P08_N,P09_N,P10_N,P11_N
0,1,20.5,211.132445,472.106499,59016.780458,180.278488,0.004718,4.598,1.309762,0.657530,...,0.054845,0.054845,0.355741,0.927652,0.009837,0.349467,0.257006,0.275423,0.280247,0.160595
1,2,18.2,608.912622,1361.570015,102354.648132,27.941448,0.027554,4.406,1.340600,0.634973,...,0.159917,0.159917,0.630377,0.142520,0.057622,0.319392,0.268756,0.262745,0.295111,0.150236
2,3,22.0,105.816886,236.613750,18512.294286,65.706055,0.143739,4.892,1.332637,0.640673,...,0.027026,0.027026,0.099060,0.337155,0.300752,0.395520,0.265721,0.265949,0.116911,0.874766
3,4,18.8,461.907460,1032.856481,79985.334528,168.575485,0.026491,4.760,1.365668,0.617570,...,0.121086,0.121086,0.488621,0.867336,0.055399,0.374843,0.278307,0.252965,0.187345,0.637991
4,5,24.4,35.039264,78.350176,68753.886594,66.274681,0.055444,6.006,0.977089,1.020477,...,0.008330,0.008330,0.417446,0.340086,0.115985,0.570019,0.130255,0.479401,0.026955,0.657124

# 2-2

In [33]:
stds = []

In [34]:
tmp = []

for target in targets:
    tmp.append(target + '_N')

In [35]:
targets = tmp

In [36]:
targets

['P01_N',
 'P02_N',
 'P03_N',
 'P04_N',
 'P05_N',
 'P06_N',
 'P07_N',
 'P08_N',
 'P09_N',
 'P10_N',
 'P11_N']

In [37]:
for target in targets:
    std = df_2[target].std()
    stds.append(std)

In [38]:
std

np.float64(0.1961138843826473)

In [39]:
stds

[np.float64(0.1711087039598908),
 np.float64(0.08125046881838696),
 np.float64(0.08125046881838495),
 np.float64(0.17398571304628524),
 np.float64(0.28939906555824113),
 np.float64(0.16119491646329084),
 np.float64(0.19427596140014178),
 np.float64(0.19268174364789284),
 np.float64(0.19328476566592645),
 np.float64(0.18663367412688836),
 np.float64(0.1961138843826473)]

In [40]:
len(stds)

11

In [41]:
tmp = pd.DataFrame(data=stds, columns=["std"])

In [42]:
tmp

         std
0   0.171109
1   0.081250
2   0.081250
3   0.173986
4   0.289399
5   0.161195
6   0.194276
7   0.192682
8   0.193285
9   0.186634
10  0.196114

In [45]:
tmp.sort_values(by='std', ascending=False)

         std
4   0.289399
10  0.196114
6   0.194276
8   0.193285
7   0.192682
9   0.186634
3   0.173986
0   0.171109
5   0.161195
1   0.081250
2   0.081250

In [47]:
VAR22 = ['P05', 'P11']

# 2-3

In [48]:
from scipy.stats import pearsonr

In [49]:
p = pearsonr(x=df_2[VAR22[0]], y=df_2[VAR22[1]])

In [50]:
p

PearsonRResult(statistic=np.float64(-0.12265890607171813), pvalue=np.float64(1.3695572334971058e-06))

In [51]:
p = abs(p[0])

In [52]:
p

np.float64(0.12265890607171813)

# Q2 Answer

In [53]:
print(round(p, 3))

0.123

# Q3

In [54]:
df_3 = INSPECTION.copy()

# 3-1

In [55]:
targets = ['P01', 'P02', 'P03', 'P04', 'P05', 'P06', 'P07', 'P08', 'P09', 'P10', 'P11']

In [56]:
from sklearn.preprocessing import StandardScaler

In [57]:
for target in targets:
    df_3[target + '_S'] = StandardScaler().fit_transform(X=df_3.loc[:, [target]])

In [58]:
df_3.head()

,PROD_ID,P01,P02,P03,P04,P05,P06,P07,P08,P09,...,P02_S,P03_S,P04_S,P05_S,P06_S,P07_S,P08_S,P09_S,P10_S,P11_S
0,1,20.5,211.132445,472.106499,59016.780458,180.278488,0.004718,4.598,1.309762,0.657530,...,-0.128324,-0.128324,0.155865,1.379296,-0.706791,-0.402089,-0.127122,-0.279032,0.375930,-2.025131
1,2,18.2,608.912622,1361.570015,102354.648132,27.941448,0.027554,4.406,1.340600,0.634973,...,1.165291,1.165291,1.734877,-1.334561,-0.410250,-0.556946,-0.066122,-0.344642,0.455600,-2.077972
2,3,22.0,105.816886,236.613750,18512.294286,65.706055,0.143739,4.892,1.332637,0.640673,...,-0.470819,-0.470819,-1.319912,-0.661792,1.098538,-0.164965,-0.081874,-0.328063,-0.499521,1.617660
3,4,18.8,461.907460,1032.856481,79985.334528,168.575485,0.026491,4.760,1.365668,0.617570,...,0.687217,0.687217,0.919853,1.170809,-0.424050,-0.271429,-0.016537,-0.395260,-0.122011,0.409934
4,5,24.4,35.039264,78.350176,68753.886594,66.274681,0.055444,6.006,0.977089,1.020477,...,-0.700994,-0.700994,0.510636,-0.651662,-0.048069,0.733527,-0.785159,0.776636,-0.981670,0.507530

# 3-2

In [59]:
TRAIN23 = df_3[df_3['PROD_ID'] % 5 != 0].copy()
TEST23 = df_3[df_3['PROD_ID'] % 5 == 0].copy()

In [60]:
TRAIN23.shape

(1233, 24)

In [61]:
TEST23.shape

(308, 24)

# 3-3

In [62]:
ks = [3, 5, 7]
models = []

In [63]:
tmp = []

for target in targets:
    tmp.append(target + '_S')

In [64]:
targets = tmp

In [65]:
targets

['P01_S',
 'P02_S',
 'P03_S',
 'P04_S',
 'P05_S',
 'P06_S',
 'P07_S',
 'P08_S',
 'P09_S',
 'P10_S',
 'P11_S']

In [66]:
from sklearn.neighbors import KNeighborsClassifier

In [67]:
for k in ks:
    model = KNeighborsClassifier(n_neighbors=k, metric='euclidean').fit(y=TRAIN23['DEFECT'], X=TRAIN23.loc[:, targets])
    models.append(model)

# 3-4

In [68]:
accs = []

In [69]:
from sklearn.metrics import accuracy_score

In [70]:
for model in models:
    pred = model.predict(X=TEST23.loc[:, targets])
    accs.append(accuracy_score(y_true=TEST23['DEFECT'], y_pred=pred))

In [71]:
accs

[0.8993506493506493, 0.9090909090909091, 0.9025974025974026]

# 3-5

In [74]:
ans = pd.DataFrame(accs, columns=['acc'])

In [75]:
ans['acc'].mean()

np.float64(0.9036796536796537)

In [76]:
ans

        acc
0  0.899351
1  0.909091
2  0.902597

# Q3 Answer

In [77]:
print(round(ans['acc'].mean(), 3))

0.904