In [37]:
import pandas as pd

In [38]:
POWER = pd.read_csv('lv2-2408.csv')

In [39]:
POWER.shape

(2781, 10)

In [40]:
POWER.head()

,DATE,SEASON,WEEKDAY,FAC,F1,F2,F3,F4,F5,F6
0,2020-08-31,summer,Mon,Northern,624.23,484.21,30.36,35.57,273.27,320.81
1,2020-08-31,summer,Mon,Western,1106.89,1024.33,25.17,3.81,72.00,21.53
2,2020-08-31,summer,Mon,Southern,576.66,578.55,62.73,49.80,111.57,64.78
3,2020-09-01,fall,Tue,Northern,624.23,507.42,30.36,35.69,273.27,317.19
4,2020-09-01,fall,Tue,Western,1106.89,1050.91,25.17,3.83,72.00,23.97

# Q1

In [41]:
df_1 = POWER.copy()

# 1-1

In [42]:
df_1.columns

Index(['DATE', 'SEASON', 'WEEKDAY', 'FAC', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6'], dtype='object')

In [43]:
targets = ['F1', 'F2', 'F3', 'F4', 'F5', 'F6']

In [44]:
for target in targets:
    df_1[target + '_O'] = (df_1[target] > df_1.groupby(['SEASON', 'FAC'])[target].transform(lambda x: x.quantile(0.5)) + 2 * (df_1.groupby(['SEASON', 'FAC'])[target].transform(lambda x: x.quantile(0.75)) - df_1.groupby(['SEASON', 'FAC'])[target].transform(lambda x: x.quantile(0.25)))) + 0

In [45]:
df_1.head()

,DATE,SEASON,WEEKDAY,FAC,F1,F2,F3,F4,F5,F6,F1_O,F2_O,F3_O,F4_O,F5_O,F6_O
0,2020-08-31,summer,Mon,Northern,624.23,484.21,30.36,35.57,273.27,320.81,0,0,0,0,0,0
1,2020-08-31,summer,Mon,Western,1106.89,1024.33,25.17,3.81,72.00,21.53,0,0,0,0,1,0
2,2020-08-31,summer,Mon,Southern,576.66,578.55,62.73,49.80,111.57,64.78,0,0,0,0,0,0
3,2020-09-01,fall,Tue,Northern,624.23,507.42,30.36,35.69,273.27,317.19,0,0,0,0,0,0
4,2020-09-01,fall,Tue,Western,1106.89,1050.91,25.17,3.83,72.00,23.97,0,0,0,0,0,0

In [49]:
df_1['OUT'] = ((df_1['F1_O'] + df_1['F2_O'] + df_1['F3_O'] + df_1['F4_O'] + df_1['F5_O'] + df_1['F6_O']) > 0)  + 0

In [50]:
df_1.head()

,DATE,SEASON,WEEKDAY,FAC,F1,F2,F3,F4,F5,F6,F1_O,F2_O,F3_O,F4_O,F5_O,F6_O,OUT
0,2020-08-31,summer,Mon,Northern,624.23,484.21,30.36,35.57,273.27,320.81,0,0,0,0,0,0,0
1,2020-08-31,summer,Mon,Western,1106.89,1024.33,25.17,3.81,72.00,21.53,0,0,0,0,1,0,1
2,2020-08-31,summer,Mon,Southern,576.66,578.55,62.73,49.80,111.57,64.78,0,0,0,0,0,0,0
3,2020-09-01,fall,Tue,Northern,624.23,507.42,30.36,35.69,273.27,317.19,0,0,0,0,0,0,0
4,2020-09-01,fall,Tue,Western,1106.89,1050.91,25.17,3.83,72.00,23.97,0,0,0,0,0,0,0

# 1-2

In [52]:
df_1.groupby(['SEASON', 'FAC'])['OUT'].mean().reset_index()['OUT'].max()

np.float64(0.32065217391304346)

# Q1 Answer

In [53]:
print(round(df_1.groupby(['SEASON', 'FAC'])['OUT'].mean().reset_index()['OUT'].max(), 4))

0.3207

# Q2

In [54]:
df_2 = POWER.copy()

In [55]:
df_2.shape

(2781, 10)

In [56]:
df_2.head()

,DATE,SEASON,WEEKDAY,FAC,F1,F2,F3,F4,F5,F6
0,2020-08-31,summer,Mon,Northern,624.23,484.21,30.36,35.57,273.27,320.81
1,2020-08-31,summer,Mon,Western,1106.89,1024.33,25.17,3.81,72.00,21.53
2,2020-08-31,summer,Mon,Southern,576.66,578.55,62.73,49.80,111.57,64.78
3,2020-09-01,fall,Tue,Northern,624.23,507.42,30.36,35.69,273.27,317.19
4,2020-09-01,fall,Tue,Western,1106.89,1050.91,25.17,3.83,72.00,23.97

# 2-1

In [57]:
df_2 = df_2[df_2['FAC'] == 'Northern'].copy()

In [58]:
df_2.shape

(927, 10)

In [59]:
df_2['FAC'].value_counts()

FAC
Northern    927
Name: count, dtype: int64

# 2-2

In [60]:
df_2['TOTAL'] = df_1['F1'] + df_1['F2'] + df_1['F3'] + df_1['F4'] + df_1['F5'] + df_1['F6']

In [61]:
df_2.head()

,DATE,SEASON,WEEKDAY,FAC,F1,F2,F3,F4,F5,F6,TOTAL
0,2020-08-31,summer,Mon,Northern,624.23,484.21,30.36,35.57,273.27,320.81,1768.45
3,2020-09-01,fall,Tue,Northern,624.23,507.42,30.36,35.69,273.27,317.19,1788.16
6,2020-09-02,fall,Wed,Northern,624.23,492.69,30.36,35.65,273.27,316.69,1772.89
9,2020-09-03,fall,Thu,Northern,624.23,568.34,30.36,35.62,273.27,297.47,1829.29
12,2020-09-04,fall,Fri,Northern,628.58,597.08,30.36,35.72,273.27,290.23,1855.24

In [66]:
df_2.groupby('SEASON')['TOTAL'].mean().reset_index()

   SEASON        TOTAL
0    fall  1695.685147
1  spring  1676.009104
2  summer  2011.511196
3  winter  1521.046519

In [68]:
df_2.groupby('SEASON')['TOTAL'].std().reset_index()

   SEASON       TOTAL
0    fall  197.841970
1  spring  181.620801
2  summer   95.634489
3  winter   44.843249

In [64]:
df_2.groupby('SEASON')['TOTAL'].count()

SEASON
fall      272
spring    201
summer    184
winter    270
Name: TOTAL, dtype: int64

# 2-3

In [69]:
summary = pd.DataFrame(data=['fall', 'spring', 'summer', 'winter'], columns=['season'])

In [70]:
summary['mean'] = df_2.groupby('SEASON')['TOTAL'].mean().reset_index()['TOTAL']

In [72]:
summary['std'] = df_2.groupby('SEASON')['TOTAL'].std().reset_index()['TOTAL']

In [74]:
summary['count'] = df_2.groupby('SEASON')['TOTAL'].count().reset_index()['TOTAL']

In [75]:
summary

   season         mean         std  count
0    fall  1695.685147  197.841970    272
1  spring  1676.009104  181.620801    201
2  summer  2011.511196   95.634489    184
3  winter  1521.046519   44.843249    270

In [86]:
summary['min_z'] = summary['mean'] - (220 / (summary['count'] ** 0.5)) * 1.64

In [87]:
summary['max_z'] = summary['mean'] + (220 / (summary['count'] ** 0.5)) * 1.64

In [88]:
summary

   season         mean         std  count        min_z        max_z     conf_l
0    fall  1695.685147  197.841970    272  1673.808434  1717.561860  39.346655
1  spring  1676.009104  181.620801    201  1650.560235  1701.457974  42.018583
2  summer  2011.511196   95.634489    184  1984.912667  2038.109725  23.124879
3  winter  1521.046519   44.843249    270  1499.088930  1543.004107   8.951360

In [89]:
summary['conf_l'] = summary['max_z'] - summary['min_z']

In [90]:
summary

   season         mean         std  count        min_z        max_z     conf_l
0    fall  1695.685147  197.841970    272  1673.808434  1717.561860  43.753427
1  spring  1676.009104  181.620801    201  1650.560235  1701.457974  50.897740
2  summer  2011.511196   95.634489    184  1984.912667  2038.109725  53.197058
3  winter  1521.046519   44.843249    270  1499.088930  1543.004107  43.915177

# 2-4

In [91]:
summary['conf_l'].max()

np.float64(53.19705778068692)

# Q2 Answer

In [92]:
print(round(summary['conf_l'].max(), 1))

53.2

# Q3

In [150]:
df_3 = POWER.copy()

In [151]:
df_3.shape

(2781, 10)

# 3-1

In [152]:
df_3 = df_3[(df_3['F1'] != 0) & (df_3['F2'] != 0) & (df_3['F3'] != 0) & (df_3['F4'] != 0) & (df_3['F5'] != 0) & (df_3['F6'] != 0)]

In [153]:
df_3.shape

(2778, 10)

In [154]:
df_3 = df_3.sort_values(by=['DATE', 'FAC'])

In [155]:
# df_3 = df_3.sort_values(by='FAC')

In [156]:
# df_3 = df_3.reset_index()

In [157]:
df_3

,DATE,SEASON,WEEKDAY,FAC,F1,F2,F3,F4,F5,F6
0,2020-08-31,summer,Mon,Northern,624.23,484.21,30.36,35.57,273.27,320.81
2,2020-08-31,summer,Mon,Southern,576.66,578.55,62.73,49.80,111.57,64.78
1,2020-08-31,summer,Mon,Western,1106.89,1024.33,25.17,3.81,72.00,21.53
3,2020-09-01,fall,Tue,Northern,624.23,507.42,30.36,35.69,273.27,317.19
5,2020-09-01,fall,Tue,Southern,576.66,562.79,62.73,52.76,111.57,59.49
...,...,...,...,...,...,...,...,...,...,...
2777,2023-03-16,spring,Thu,Southern,639.01,599.81,67.16,65.43,81.21,88.48
2776,2023-03-16,spring,Thu,Western,1326.61,1242.03,45.47,40.79,31.53,59.12
2778,2023-03-17,spring,Fri,Northern,683.49,439.09,26.23,30.37,124.40,141.16
2780,2023-03-17,spring,Fri,Southern,639.01,619.75,67.16,67.40,81.21,77.41
2779,2023-03-17,spring,Fri,Western,1326.61,1295.95,45.47,40.66,31.53,62.85

# 3-2

In [158]:
df_3['F6_NEXT'] = df_3.groupby('FAC')['F6'].shift(-1)

In [159]:
df_3.head()

,DATE,SEASON,WEEKDAY,FAC,F1,F2,F3,F4,F5,F6,F6_NEXT
0,2020-08-31,summer,Mon,Northern,624.23,484.21,30.36,35.57,273.27,320.81,317.19
2,2020-08-31,summer,Mon,Southern,576.66,578.55,62.73,49.80,111.57,64.78,59.49
1,2020-08-31,summer,Mon,Western,1106.89,1024.33,25.17,3.81,72.00,21.53,23.97
3,2020-09-01,fall,Tue,Northern,624.23,507.42,30.36,35.69,273.27,317.19,316.69
5,2020-09-01,fall,Tue,Southern,576.66,562.79,62.73,52.76,111.57,59.49,47.53

In [160]:
pd.notna(df_3['F6_NEXT'])

0        True
2        True
1        True
3        True
5        True
        ...
2777     True
2776     True
2778    False
2780    False
2779    False
Name: F6_NEXT, Length: 2778, dtype: bool

In [161]:
df_3.dropna(subset=['F6_NEXT'])

,DATE,SEASON,WEEKDAY,FAC,F1,F2,F3,F4,F5,F6,F6_NEXT
0,2020-08-31,summer,Mon,Northern,624.23,484.21,30.36,35.57,273.27,320.81,317.19
2,2020-08-31,summer,Mon,Southern,576.66,578.55,62.73,49.80,111.57,64.78,59.49
1,2020-08-31,summer,Mon,Western,1106.89,1024.33,25.17,3.81,72.00,21.53,23.97
3,2020-09-01,fall,Tue,Northern,624.23,507.42,30.36,35.69,273.27,317.19,316.69
5,2020-09-01,fall,Tue,Southern,576.66,562.79,62.73,52.76,111.57,59.49,47.53
...,...,...,...,...,...,...,...,...,...,...,...
2774,2023-03-15,spring,Wed,Southern,639.01,579.85,67.16,51.29,81.21,64.32,88.48
2773,2023-03-15,spring,Wed,Western,1326.61,1182.94,45.47,40.93,31.53,39.30,59.12
2775,2023-03-16,spring,Thu,Northern,683.49,408.49,21.76,30.53,124.40,138.34,141.16
2777,2023-03-16,spring,Thu,Southern,639.01,599.81,67.16,65.43,81.21,88.48,77.41
2776,2023-03-16,spring,Thu,Western,1326.61,1242.03,45.47,40.79,31.53,59.12,62.85

In [162]:
pd.notna(df_3['F6_NEXT'])

0        True
2        True
1        True
3        True
5        True
        ...
2777     True
2776     True
2778    False
2780    False
2779    False
Name: F6_NEXT, Length: 2778, dtype: bool

In [163]:
df_3 = df_3.dropna(subset=['F6_NEXT'])
df_3.shape

(2775, 11)

# 3-3

In [164]:
TRAIN3 = df_3[df_3['DATE'] < '2022-09-01'].copy()
TEST3 = df_3[df_3['DATE'] >= '2022-09-01'].copy()

In [165]:
TRAIN3.shape

(2184, 11)

In [166]:
TEST3.shape

(591, 11)

# 3-4

In [167]:
from sklearn.linear_model import LinearRegression

In [168]:
targets = ['F1', 'F2', 'F3', 'F4', 'F5', 'F6']

In [169]:
model = LinearRegression().fit(y=TRAIN3['F6_NEXT'], X=TRAIN3.loc[:, targets])

# 3-5

In [170]:
pred = model.predict(X=TEST3.loc[:, targets])

In [171]:
from sklearn.metrics import mean_absolute_percentage_error

In [172]:
mape = mean_absolute_percentage_error(y_true=TEST3['F6_NEXT'], y_pred=pred)

In [173]:
mape

0.0863922344752276

# Q3 Answer

In [174]:
print(round(mape * 100, 3))

8.639