In [1]:
import pandas as pd
import numpy as np

In [2]:
FAC = pd.read_csv('lv2-2405.csv')

# Q1

In [3]:
df_1 = FAC.copy()

# 1-1

In [4]:
FAC0 = df_1[df_1['FAIL_YN'] == 0].copy()

In [5]:
FAC0.shape

(965, 7)

In [6]:
FAC1 = df_1[df_1['FAIL_YN'] == 1].copy()

In [7]:
FAC1.shape

(41, 7)

# 1-2

In [12]:
cvs_0 = []
cvs_1 = []

In [9]:
FAC0.columns

Index(['PRD_ID', 'ROT_SPD', 'TRQ_PWR', 'DUR', 'NS', 'TEMP_DIFF', 'FAIL_YN'], dtype='object')

In [10]:
targets = ['TRQ_PWR', 'DUR', 'NS', 'TEMP_DIFF']

In [11]:
len(targets)

4

In [13]:
for target in targets:
    s_0 = FAC0[target].std()
    x_0 = FAC0[target].mean()
    cv_0 = s_0 / x_0

    s_1 = FAC1[target].std()
    x_1 = FAC1[target].mean()
    cv_1 = s_1 / x_1

    cvs_0.append(cv_0)
    cvs_1.append(cv_1)

# 1-3

In [16]:
gaps = []

for i in range(4):
    gaps.append(abs(cvs_0[i] - cvs_1[i]))

In [17]:
gaps

[np.float64(0.20193552889678829),
 np.float64(0.014137329518960073),
 np.float64(0.01138566641172177),
 np.float64(0.037607160411578786)]

In [18]:
max(gaps)

np.float64(0.20193552889678829)

# Q1 Answer

In [19]:
print(round(max(gaps), 3))

0.202

# Q2

In [35]:
df_2 = FAC.copy()

In [36]:
df_2.shape

(1006, 7)

In [37]:
df_2.head()

   PRD_ID  ROT_SPD  TRQ_PWR  DUR   NS  TEMP_DIFF  FAIL_YN
0       1   1442.0       49  165   97        9.5        0
1       2   1679.0       31   79   91        9.6        0
2       3   1492.0       41  150   96        9.6        0
3       4   1498.0       47  199  110       10.7        0
4       5   1376.0       46  210  106        8.5        1

# 2-1

In [38]:
DF5 = df_2.dropna(subset='ROT_SPD')

In [39]:
DF5.shape

(991, 7)

# 2-2

In [40]:
from sklearn.preprocessing import StandardScaler

In [41]:
DF5.columns

Index(['PRD_ID', 'ROT_SPD', 'TRQ_PWR', 'DUR', 'NS', 'TEMP_DIFF', 'FAIL_YN'], dtype='object')

In [42]:
targets = ['ROT_SPD', 'TRQ_PWR', 'DUR', 'NS', 'TEMP_DIFF']

In [43]:
len(targets)

5

In [44]:
for target in targets:
    DF5[target + '_S'] = StandardScaler().fit_transform(X=DF5.loc[:, [target]])

C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_18768\2887053666.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF5[target + '_S'] = StandardScaler().fit_transform(X=DF5.loc[:, [target]])
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_18768\2887053666.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF5[target + '_S'] = StandardScaler().fit_transform(X=DF5.loc[:, [target]])
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_18768\2887053666.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF5[target + '_S'] = StandardScaler().fit_transform(X=DF5.loc[:, [target]])
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_18768\2887053666.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF5[target + '_S'] = StandardScaler().fit_transform(X=DF5.loc[:, [target]])
C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_18768\2887053666.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF5[target + '_S'] = StandardScaler().fit_transform(X=DF5.loc[:, [target]])

In [45]:
DF5

,PRD_ID,ROT_SPD,TRQ_PWR,DUR,NS,TEMP_DIFF,FAIL_YN,ROT_SPD_S,TRQ_PWR_S,DUR_S,NS_S,TEMP_DIFF_S
0,1,1442.0,49,165,97,9.5,0,-0.511206,0.893629,0.867364,-0.771185,-0.001684
1,2,1679.0,31,79,91,9.6,0,0.760403,-0.916769,-0.502271,-1.248242,0.109599
2,3,1492.0,41,150,96,9.6,0,-0.242934,0.089008,0.628474,-0.850695,0.109599
3,4,1498.0,47,199,110,10.7,0,-0.210741,0.692474,1.408848,0.262437,1.333715
4,5,1376.0,46,210,106,8.5,1,-0.865325,0.591896,1.584034,-0.055600,-1.114517
...,...,...,...,...,...,...,...,...,...,...,...,...
1000,1001,1565.0,36,140,122,9.5,0,0.148743,-0.413881,0.469214,1.216550,-0.001684
1002,1003,1463.0,46,182,109,9.3,0,-0.398531,0.591896,1.138106,0.182928,-0.224251
1003,1004,1586.0,34,149,119,8.0,0,0.261418,-0.615036,0.612548,0.978022,-1.670934
1004,1005,1902.0,24,129,126,9.5,0,1.956896,-1.620813,0.294028,1.534588,-0.001684
1005,1006,1510.0,40,134,101,10.2,0,-0.146356,-0.011570,0.373658,-0.453148,0.777299

# 2-3

In [46]:
from sklearn.cluster import KMeans

In [47]:
targets

['ROT_SPD', 'TRQ_PWR', 'DUR', 'NS', 'TEMP_DIFF']

In [48]:
tmp = []

for target in targets:
    tmp.append(target + '_S')

In [49]:
targets = tmp

In [50]:
targets

['ROT_SPD_S', 'TRQ_PWR_S', 'DUR_S', 'NS_S', 'TEMP_DIFF_S']

In [51]:
model = KMeans(n_clusters=3, n_init=5, random_state=1234).fit(X=DF5.loc[:, targets])

# 2-4

In [52]:
DF5['LABEL'] = model.predict(X=DF5.loc[:, targets])

C:\Users\eunsang.jeon\AppData\Local\Temp\ipykernel_18768\1630164199.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DF5['LABEL'] = model.predict(X=DF5.loc[:, targets])

In [53]:
DF5

,PRD_ID,ROT_SPD,TRQ_PWR,DUR,NS,TEMP_DIFF,FAIL_YN,ROT_SPD_S,TRQ_PWR_S,DUR_S,NS_S,TEMP_DIFF_S,LABEL
0,1,1442.0,49,165,97,9.5,0,-0.511206,0.893629,0.867364,-0.771185,-0.001684,0
1,2,1679.0,31,79,91,9.6,0,0.760403,-0.916769,-0.502271,-1.248242,0.109599,2
2,3,1492.0,41,150,96,9.6,0,-0.242934,0.089008,0.628474,-0.850695,0.109599,0
3,4,1498.0,47,199,110,10.7,0,-0.210741,0.692474,1.408848,0.262437,1.333715,0
4,5,1376.0,46,210,106,8.5,1,-0.865325,0.591896,1.584034,-0.055600,-1.114517,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,1001,1565.0,36,140,122,9.5,0,0.148743,-0.413881,0.469214,1.216550,-0.001684,0
1002,1003,1463.0,46,182,109,9.3,0,-0.398531,0.591896,1.138106,0.182928,-0.224251,0
1003,1004,1586.0,34,149,119,8.0,0,0.261418,-0.615036,0.612548,0.978022,-1.670934,1
1004,1005,1902.0,24,129,126,9.5,0,1.956896,-1.620813,0.294028,1.534588,-0.001684,1
1005,1006,1510.0,40,134,101,10.2,0,-0.146356,-0.011570,0.373658,-0.453148,0.777299,0

In [56]:
DF5['LABEL'].value_counts()

LABEL
2    414
0    365
1    212
Name: count, dtype: int64

In [57]:
DF5[DF5['FAIL_YN'] == 1]['LABEL'].value_counts()

LABEL
0    24
1    11
2     6
Name: count, dtype: int64

In [62]:
arr = [24/365*100, 11/212*100, 6/414*100]
arr

[6.575342465753424, 5.188679245283019, 1.4492753623188406]

In [61]:
abs(max(arr) - min(arr))

5.1260671034345835

# Q2 Answer

In [63]:
print(round(abs(max(arr) - min(arr)), 2))

5.13

# Q3

In [77]:
df_3 = FAC.copy()

In [78]:
df_3.shape

(1006, 7)

In [79]:
df_3.head()

   PRD_ID  ROT_SPD  TRQ_PWR  DUR   NS  TEMP_DIFF  FAIL_YN
0       1   1442.0       49  165   97        9.5        0
1       2   1679.0       31   79   91        9.6        0
2       3   1492.0       41  150   96        9.6        0
3       4   1498.0       47  199  110       10.7        0
4       5   1376.0       46  210  106        8.5        1

# 3-1

In [80]:
tmp = df_3.dropna(subset='ROT_SPD')

In [81]:
tmp.shape

(991, 7)

In [82]:
tmp['ROT_SPD'].median()

np.float64(1506.0)

In [83]:
df_3['ROT_SPD'] = df_3['ROT_SPD'].fillna(value=tmp['ROT_SPD'].median())

In [84]:
df_3

      PRD_ID  ROT_SPD  TRQ_PWR  DUR   NS  TEMP_DIFF  FAIL_YN
0          1   1442.0       49  165   97        9.5        0
1          2   1679.0       31   79   91        9.6        0
2          3   1492.0       41  150   96        9.6        0
3          4   1498.0       47  199  110       10.7        0
4          5   1376.0       46  210  106        8.5        1
...      ...      ...      ...  ...  ...        ...      ...
1001    1002   1506.0       43  174  103        8.8        0
1002    1003   1463.0       46  182  109        9.3        0
1003    1004   1586.0       34  149  119        8.0        0
1004    1005   1902.0       24  129  126        9.5        0
1005    1006   1510.0       40  134  101       10.2        0

[1006 rows x 7 columns]

In [85]:
tmp = df_3.dropna(subset='ROT_SPD')

In [86]:
tmp.shape

(1006, 7)

# 3-2

In [87]:
TRAIN6 = df_3[df_3['PRD_ID'] % 3 != 0]
TEST6 = df_3[df_3['PRD_ID'] % 3 == 0]

In [88]:
TRAIN6.shape

(671, 7)

In [89]:
TEST6.shape

(335, 7)

# 3-3

In [90]:
from sklearn.tree import DecisionTreeClassifier

In [91]:
df_3.columns

Index(['PRD_ID', 'ROT_SPD', 'TRQ_PWR', 'DUR', 'NS', 'TEMP_DIFF', 'FAIL_YN'], dtype='object')

In [93]:
targets = ['ROT_SPD', 'TRQ_PWR', 'DUR', 'NS', 'TEMP_DIFF']

In [94]:
model = DecisionTreeClassifier(random_state=3, min_samples_split=3).fit(y=TRAIN6['FAIL_YN'], X=TRAIN6.loc[:, targets])

In [107]:
models = []
ks = [3, 5, 7]

for k in ks:
    model = DecisionTreeClassifier(random_state=3, min_samples_split=3, max_depth=k).fit(y=TRAIN6['FAIL_YN'], X=TRAIN6.loc[:, targets])
    models.append(model)

# 3-4

In [108]:
recs = []

In [109]:
from sklearn.metrics import recall_score

In [110]:
for model in models:
    pred = model.predict(X=TRAIN6.loc[:, targets])
    recs.append(recall_score(y_true=TRAIN6['FAIL_YN'], y_pred=pred))

In [111]:
recs

[0.37037037037037035, 0.6296296296296297, 0.7407407407407407]

# 3-5

In [113]:
pred = models[2].predict(X=TEST6.loc[:, targets])

In [114]:
recall_score(y_true=TEST6['FAIL_YN'], y_pred=pred)

0.6428571428571429

# Q3 Answer

In [115]:
print(round(0.6428571428571429, 3))

0.643